title:            Jordi Pont-Tuset's site
description:      Welcome to my site.
# Your site's domain goes here. Leave localhost server or blank when working locally.
url:              //zgojcic.github.io
#http://localhost:5000
#https://jponttuset.github.io
disqus_shortname: zgojcic

# Owner/author information
owner:
  name:          Zan Gojcic
  avatar:         zan.jpg
  bio:            From a small town near Maribor Slovenia. Currently a PhD student at ETH Zürich. Love good food, traveling and football.
  email:          zan.gojcic@geod.baug.ethz.ch
  # Social networking links are used in author-bio sidebar. Update and remove as you like.
  github: zgojcic
  google_scholar: 8KsqL4gAAAAJ&hl=en
  research_gate:  Zan_Gojcic
  twitter: zgojcic
  linkedin: zgojcic
  
  

# Links to include in top navigation
# For external links add external: true
links:
  - title: About
    url: /about/
  - title: Resume
    url: /resume/
  - title: Projects
    url: /projects/
  - title: Blog
    url: /blog/

# http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
timezone:    Europe/Zurich
future:      true
#pygments:    true
highlighter: rouge
markdown:    kramdown
kramdown:
  extensions: ["strikethrough"]
  
# https://github.com/mojombo/jekyll/wiki/Permalinks
permalink:   /:categories/:title/

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  enable_coderay: false

  coderay:
    coderay_line_numbers:
    coderay_line_numbers_start: 1
    coderay_tab_width: 4
    coderay_bold_every: 10
    coderay_css: class

include: [".htaccess"]
exclude: ["lib", "config.rb", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp", "less", "*.sublime-project", "*.sublime-workspace", "test", "spec", "Gruntfile.js", "package.json", "node_modules", "Gemfile", "Gemfile.lock", "LICENSE", "README.md"]
